#define SECRET_WIFI_SSID "YOUR-SSID"
#define SECRET_WIFI_PASSWORD "YOUR-PASSWORD"
#define SECRET_MQTT_USER "YOUR-MQTT-USER"
#define SECRET_MQTT_PASSWORD "YOUR-MQTT-PASSWORD"
#define SECRET_MQTT_HOST "YOUR-MQTT-HOST"
#define SECRET_MQTT_TOPIC "YOUR-MQTT-TOPIC"
#define SECRET_MQTT_PORT "YOUR-MQTT-PORT"
#define SECRET_MQTT_CLIENT_ID "YOUR-MQTT-CLIENT-ID"

